language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t fjacky/udagram-feed-service udagram-feed-service/
  - docker build -t fjacky/udagram-user-service udagram-user-service/
  - docker build -t fjacky/udagram-frontend udagram-frontend/
  - docker build -t fjacky/reverse-proxy reverse-proxy/
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fjacky/udagram-feed-service
  - docker push fjacky/udagram-user-service
  - docker push fjacky/udagram-frontend
  - docker push fjacky/reverse-proxy
