# FILE IS ON GITIGNORE, SET VALUES AND DO NOT COMMIT
export POSTGRES_USERNAME=PLACEHOLDER
export POSTGRES_PASSWORD=PLACEHOLDER
export POSTGRES_HOST=PLACEHOLDER
export POSTGRES_DATABASE=PLACEHOLDER
export AWS_BUCKET=PLACEHOLDER
export AWS_REGION=PLACEHOLDER
export AWS_PROFILE=PLACEHOLDER
export AWS_EKS_CLUSTER=PLACEHOLDER
export JWT_SECRET=PLACEHOLDER
export URL=http://localhost:8100 # only used for local development, not on EKS
