apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: aws-credentials-volume
        secret:
          secretName: aws-credentials
      containers:
      - name: frontend
        image: fjacky/udagram-frontend
        ports:
        - containerPort: 80
      restartPolicy: Always
      

